[package]
name = "minigame"
version = "0.1.0"
edition = "2024"

[dependencies]
bevior_tree = "0.8.0"
bevy = "0.16.1"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] } 
serde_json = "1.0.140"
thiserror = "2.0.12"
